### ISSUE TITLE
Return code: 251, voxel size is different, first make conform

### ISSUE THREAD

**Issue by hensel-f** [poldracklab/smriprep#198] opened 2020-05-29 13:55 UTC
I'm trying to use `smriprep` to process a BIDS-directory containing (in this minimal working example) two MRI-images of a single subject.
However, the following command:

```
sudo docker run -ti --rm \
     -v <my path to fs-license>:/fs-license:ro \
    -v <my path to data>:/data:ro \
    -v <my path to output>:/out \
    -v <my path to work>::/work \
    poldracklab/smriprep:latest \
    /data /out/out \
    participant \
    -w /work \
    --participant-label <participant label> \
    --fs-license-file /fs-license/license.txt
```

stops with the following error message:

```
Standard error:
ERROR: MultiRegistration::loadMovables: images have different voxel sizes.
  Currently not supported, maybe first make conform?
  Debug info: size(1) = 1.19784, 1.24815, 1.25342   size(0) = 1.19779, 1.24656, 1.24975
MultiRegistration::loadMovables: voxel size is different <some path in the /work-directory...>_T1w_corrected.nii.gz.

No such file or directory
Return code: 251

200529-12:42:18,659 nipype.workflow ERROR:
	 could not run node: smriprep_wf.single_subject_<participant-label>_wf.anat_preproc_wf.anat_template_wf.t1w_merge
Preprocessing did not finish successfully. Errors occurred while processing data from participants: <participant-label> (1). Check the HTML reports for details.
```

The header files of the two `.nii.gz` files in the BIDS-directory are as follows:

```
sizeof_hdr      : 348
data_type       : b''
db_name         : b'<subject-ID>'
extents         : 0
session_error   : 0
regular         : b'r'
dim_info        : 0
dim             : [  3 160 192 192   1   1   1   1]
intent_p1       : 0.0
intent_p2       : 0.0
intent_p3       : 0.0
intent_code     : none
datatype        : float32
bitpix          : 32
slice_start     : 0
pixdim          : [1.        1.1977932 1.2465563 1.2497512 1.        1.        1.         1.       ]
vox_offset      : 0.0
scl_slope       : nan
scl_inter       : nan
slice_end       : 0
slice_code      : unknown
xyzt_units      : 2
cal_max         : 0.0
cal_min         : 0.0
slice_duration  : 0.0
toffset         : 0.0
glmax           : 1667
glmin           : 0
descrip         : b'MPR-R; GradWarp; B1 Correction; N3; Scaled'
aux_file        : b'none'
qform_code      : unknown
sform_code      : aligned
quatern_b       : 0.0
quatern_c       : 0.0
quatern_d       : 0.0
qoffset_x       : -95.823456
qoffset_y       : -119.6694
qoffset_z       : -119.97612
srow_x          : [  1.1977932   0.          0.        -95.823456 ]
srow_y          : [   0.           1.2465563    0.        -119.6694   ]
srow_z          : [   0.           0.           1.2497512 -119.97612  ]
intent_name     : b''
magic           : b'n+1'
```

and:

```
sizeof_hdr      : 348
data_type       : b''
db_name         : b'<subject-ID>'
extents         : 0
session_error   : 0
regular         : b'r'
dim_info        : 0
dim             : [  3 160 192 192   1   1   1   1]
intent_p1       : 0.0
intent_p2       : 0.0
intent_p3       : 0.0
intent_code     : none
datatype        : float32
bitpix          : 32
slice_start     : 0
pixdim          : [1.        1.1978364 1.2481513 1.2534225 1.        1.        1.
 1.       ]
vox_offset      : 0.0
scl_slope       : nan
scl_inter       : nan
slice_end       : 0
slice_code      : unknown
xyzt_units      : 2
cal_max         : 0.0
cal_min         : 0.0
slice_duration  : 0.0
toffset         : 0.0
glmax           : 1664
glmin           : 0
descrip         : b'MPR; GradWarp; B1 Correction; N3; Scaled'
aux_file        : b'none'
qform_code      : unknown
sform_code      : aligned
quatern_b       : 0.0
quatern_c       : 0.0
quatern_d       : 0.0
qoffset_x       : -95.82691
qoffset_y       : -119.822525
qoffset_z       : -120.32856
srow_x          : [  1.1978364   0.          0.        -95.82691  ]
srow_y          : [   0.           1.2481513    0.        -119.822525 ]
srow_z          : [   0.           0.           1.2534225 -120.32856  ]
intent_name     : b''
magic           : b'n+1'
```

I tried adding the following options without success:
```
    --output-spaces MNI152NLin2009cAsym:res-1.2
    --longitudinal
    --no-submm-recon
```
Even though the voxel-sizes of the images are very close to each other (and to 1.2mm) the error persists.
Is it possible to get `smriprep` to execute a "conformation" step in order to get the same voxel-sizes (for example 1.2mm)  in the images?

This is my first time working with MRI-data. Any information on what exactly the issue is and how to fix it is very much appreciated. How should I proceed to successfully run `smriprep`?
Thank you very much!

**Comment by effigies** [comment] 2020-05-29 16:47
This is a duplicate of #70. Please follow up there.

**Closed by effigies** 2020-05-29 16:47 UTC
